version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=spotify-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    # restart: always
    volumes:
      - ./src/config/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - '5050:80'
    # restart: always
    depends_on:
      - postgres
