export const HTTP_GET_SONGS = 'HTTP_GET_SONGS';
export const HTTP_DOWNLOAD_SONG = 'HTTP_DOWNLOAD_SONG';
export const HTTP_IS_SEARCHING = 'HTTP_IS_SEARCHING';
export const HTTP_SEARCHES = 'HTTP_SEARCHES';
